apiVersion: v1
kind: Service
metadata:
  name: sms-frontend-nodeport
  namespace: sms
spec:
  type: NodePort
  selector:
    app: sms-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081

