apiVersion: v1
kind: Service
metadata:
  name: sms-backend-nodeport
  namespace: sms
spec:
  type: NodePort
  selector:
    app: sms-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080

